---
title: "Project title"
subtitle: "Report"
format: html
editor: visual
execute:
  echo: true
---

<<<<<<< HEAD
Duke University is intrinsically connected to its sports program. Most famously known for their Men's Division 1 Basketball and Football teams, as of 2020, Duke makes an estimated \$33,382,946 and \$39,669,829 in revenue, respectively (https://blackinblue.trinity.duke.edu/haves-and-have-nots-inequities-amongst-duke-universitys-sports-teams). Furthermore, Duke spends approximately \$1,329,949 per Men's basketball player and \$217,047 per football player (Ibid.). Duke's 2020 Equity in Athletics Disclosure Act (EADA) revealed that Duke spent a total of \$57,114,331 on men's sports teams and a total of \$25,472,405 on women's sports teams (Ibid.) This figure includes recruitment cost, amongst other things. This begs the question: is this the status quo in collegiate athletics?
=======
*Introduction*

**Context**

Duke University is intrinsically connected to its sports program. Most famously known for their Men's Division 1 Basketball and Football teams, as of 2020, Duke makes an estimated \$33,382,946 and \$39,669,829 in revenue, respectively (https://blackinblue.trinity.duke.edu/haves-and-have-nots-inequities-amongst-duke-universitys-sports-teams). Furthermore, Duke spends approximately \$1,329,949 per Men's basketball player and \$217,047 per football player (Ibid.). Duke's 2020 Equity in Athletics Disclosure Act (EADA) revealed that Duke spent a total of \$57,114,331 on men's sports teams and a total of \$25,472,405 on women's sports teams (Ibid.) This figure includes recruitment cost, amongst other things. This begs the question: is this the status quo in collegiate athletics?

**Explanation of Topic**

Our topic will specifically observe and investigate how much, on average, universities spend on recruitment. We will create a model that predicts this figure, based on the current a university's expenditure on athletic scholarships for student athletes. We will break down a number of variables within the data, looking at whether the institution is public versus private, has a football program or not, and what athletic division it falls under (I, II, or III). Our research question is: To what extent can college athletics' recruitment funds be predicted by the level of athletic scholarships provided to student athletes? We hypothesize that the ratio will, to a high degree, predict the recruitment funding --- as schools who allocate more money into students' financial aid will be willing to designate more money for their recruitment.

**Ethical Issues**

There are very few ethical issues anticipated with this investigation. However, it is important to note that source biases are an likely phenomenon. We must be careful with many self-reported information from university sites, and assuring that the data published can be verified.
>>>>>>> c2f89739d6104025a152d35e05c3c1035d33e093
